version: '3.6'
services:


### PostgreSQL ###########################################
    db_postgres:
      container_name: db_postgres
      build:
        context: ./postgres
        dockerfile: Dockerfile
      environment:
        POSTGRES_PASSWORD: mysecretpassword
        POSTGRES_USER: postgres
        POSTGRES_DB: projector_hw4
      ports:
        - 0.0.0.0:5438:5432
      volumes:
        - db-data:/var/lib/postgresql/data
        - ./postgres/docker-entrypoint-initdb.d/:/docker-entrypoint-initdb.d
      networks:
        - default

    king_size_service_7:
      container_name: king_size_service_7
      build:
        context: .
        dockerfile: Dockerfile
      ports:
        - "0.0.0.0:4888:4888"
      volumes:
        - .:/app/

      environment:
        ENV_NAME: local
        # app settings
        APP_HOST: 0.0.0.0
        APP_PORT: 4888
        LOG_LEVEL: DEBUG
        USE_PROBABILISTIC_CACHE: "true"

        # postgres settings
        POSTGRES_PASSWORD: mysecretpassword
        POSTGRES_USER: postgres
        POSTGRES_DB: projector_hw4
        POSTGRES_PORT: 5432
        POSTGRES_HOST: db_postgres

      links:
        - db_postgres
      depends_on:
        - db_postgres
      networks:
        - default

volumes:
  db-data:
  redis-data:
  influxdb_data:
  grafana_data:
